src/beans/User.java
package beans;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
	private static final long serialVersionUID = 1L;

	private int id;
	private String login_id;
	private String name;
	private String password;
	private String branch_code;
	private String department;
	private String authority;
	private Date created_date;
	private Date updated_date;


	public int getId() {
		return this.id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getLoginId() {
		return this.login_id;
	}
	public void setLoginId(String login_id) {
		this.login_id = login_id;
	}
	public String getName() {
		return this.name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getPassword() {
		return this.password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getBranchCode() {
		return this.branch_code;
	}
	public void setBranchCode(String branch_code) {
		this.branch_code = branch_code;
	}
	public String getDepartment() {
		return this.department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}
	public Date getCreatedDate() {
		return this.created_date;
	}
	public void setCreatedDate(Date created_date) {
		this.created_date = created_date;
	}
	public Date getUpdatedDate() {
		return this.updated_date;
	}
	public void setUpdatedDate(Date updated_date) {
		this.updated_date = updated_date;
	}

	public String getAuthority() {
		return this.authority;
	}
	public void setAuthority(String authority) {
		this.authority = authority;
	}
}

src/controller/LoginServlet.java
package controller;


import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import beans.User;
import service.LoginService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        request.getRequestDispatcher("/login").forward(request, response);
    }

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		String login_id = request.getParameter("login_id");
		String password = request.getParameter("password");



		LoginService loginService = new LoginService();
		User user = loginService.login(login_id, password);

		HttpSession session = request.getSession();
		if (user != null) {


				session.setAttribute("loginUser", user);
				response.sendRedirect("top");


		} else {

			List<String> messages = new ArrayList<String>();
			messages.add("ログインに失敗しました。");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("login");

		}
	}

}

src/controller/NewPostServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.Post;
import beans.User;
import service.NewPostService;


@WebServlet(urlPatterns = { "/newpost" })
public class NewPostServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        request.getRequestDispatcher("newpost.jsp").forward(request, response);
    }


    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        HttpSession session = request.getSession();

        List<String> posts = new ArrayList<String>();

        if (isValid(request, posts) == true) {

            User user = (User) session.getAttribute("loginUser");

            Post post = new Post();
            post.setUserId(user.getId());
            post.setTitle(request.getParameter("title"));
            post.setCategory(request.getParameter("category"));
            post.setText(request.getParameter("text"));
            System.out.println(post);


            new NewPostService().register(post);
            session.setAttribute("post", post); // ついか
            System.out.println(session);
            response.sendRedirect("./top");
        } else {
            session.setAttribute("errorMessages", posts);
            response.sendRedirect("newpost.jsp");
        }
    }

    private boolean isValid(HttpServletRequest request, List<String> messages) {

        String text = request.getParameter("text");
        String title = request.getParameter("title");
        String category = request.getParameter("category");


        if (StringUtils.isEmpty(text) == true) {
            messages.add("メッセージを入力してください");
        }
        if (StringUtils.isEmpty(title) == true) {
            messages.add("タイトルを入力してください");
        }
        if (StringUtils.isEmpty(category) == true) {
            messages.add("カテゴリーを入力してください");
        }
        if (1000 < text.length()) {
            messages.add("1000文字以下で入力してください");

        }
        if (30 < title.length()) {
            messages.add("タイトルは30文字以下で入力してください");

        }
        if (10 < category.length()) {
            messages.add("カテゴリーは10文字以下で入力してください");

        }
        if (messages.size() == 0) {
            return true;
        } else {
            return false;
        }
    }

}

src/controller/SignUpServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.User;
import service.UserService;

@WebServlet(urlPatterns = { "/signup" })
public class SignUpServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		request.getRequestDispatcher("signup.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		List<String> messages = new ArrayList<String>();

		HttpSession session = request.getSession();
		if (isValid(request, messages) == true) {

			User user = new User();
			user.setLoginId(request.getParameter("login_id"));
			user.setName(request.getParameter("name"));
			user.setPassword(request.getParameter("password"));
			user.setBranchCode(request.getParameter("branch_code"));
			user.setDepartment(request.getParameter("department"));
			user.setAuthority(request.getParameter("authority"));

			new UserService().register(user);

			response.sendRedirect("login.jsp");
		} else {
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("signup");
		}
	}

	private boolean isValid(HttpServletRequest request, List<String> messages) {
		String login_id = request.getParameter("login_id");
		String password = request.getParameter("password");
		String name = request.getParameter("name");
		String passwordConfirm = request.getParameter("passwordConfirm");
		String branch = request.getParameter("branch_code");
		String department = request.getParameter("department");
		String authority = request.getParameter("authority");


		if (StringUtils.isEmpty(login_id) == true) {
			messages.add("アカウント名を入力してください");
		}
		if (StringUtils.isEmpty(password) == true) {
			messages.add("パスワードを入力してください");
		}
		if (StringUtils.isEmpty(name) == true) {
			messages.add("名前を入力してください");
		}
		if (StringUtils.isEmpty(branch) == true) {
			messages.add("支店名を入力してください");
		}
		if (StringUtils.isEmpty(department) == true) {
			messages.add("部署を入力してください");
		}
		if (login_id.length()<6 || login_id.length()>20){
			messages.add("アカウント名は6～20文字以下の英数字で設定してください");
		}
////		if (!(login_id.matches("\\W*"))){
////			messages.add("アカウント名は半角英数字で設定してください");
//		}
		if (name.length() > 10){
			messages.add("名前は10文字以下で設定してください");
		}

		if(StringUtils.isEmpty(authority)==true){
			messages.add("ユーザーの状態を入力してください");
		}

		//		if (account.length() < 6 || 20 < account.length() ){
		//			messages.add("ログインIDは6文字以上20文字以下で設定してください");
		//
		//		}else if(!account.matches("[0-9A-Za-z]+$")){
		//			messages.add("ログインIDは半角英数字で設定してください");
		//			}else {
		//
		//			}


		if (!(password.equals(passwordConfirm))){
			messages.add("確認用パスワードと一致しません");
		}
		// TODO アカウントが既に利用されていないか、メールアドレスが既に登録されていないかなどの確認も必要
		if (messages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}

}

src/controller/TopServlet.java
package controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import beans.UserPost;
import service.NewPostService;



@WebServlet(urlPatterns = { "/top" })
public class TopServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {



        List<UserPost> posts = new NewPostService().getMessage();

        request.setAttribute("posts", posts);



        request.getRequestDispatcher("/top.jsp").forward(request, response);
    }
}

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>掲示板</title>
<link href="./css/style.css" rel="stylesheet" type="text/css">
</head>
<body>
	<font size=6>掲示板</font>
	<div class="main-contents">

		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>

		<form action="login" method="post">
		<p>
			<br /> <label for="login_id">ログインID</label> <input name="login_id"
				value="${loginUser.loginId}" id="login_id" /> <br /> <label
				for="password">パスワード</label> <input name="password" type="password"
				id="password" /> <br /> <input type="hidden" name="authority"
				value="${loginUser.authority}"> <input type="submit"
				value="ログイン" /> <br /> <a href="signup">新規登録</a>
				</p>
		</form>

	</div>
	<div class="copylight">Copyright(c)YukiDeguchi</div>
</body>
</html>

WebContent/newpost.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<title>投稿画面</title>
</head>
<body>
	<c:if test="${ not empty loginUser }">
		<div class="profile">
			<div class="name">
				<h2>
					<c:out value="${loginUser.name}" />
				</h2>
			</div>
			<div class="login_id">
				<c:out value="${loginUser.loginId}" />
			</div>

		</div>
	</c:if>

	新規投稿
	<br />

<c:if test="${ not empty errorMessages }">
				<div class="errorMessages">
					<ul>
						<c:forEach items="${errorMessages}" var="message">
							<li><c:out value="${message}" />
						</c:forEach>
					</ul>
				</div>
				<c:remove var="errorMessages" scope="session"/>
			</c:if>

	<form action="newpost" method="post">
		<br /> <label for="title">Title</label> <input name="title"
			value="${tittle}" id=title /> <br /> <label for="category">Category</label>
		<textarea name="category" cols="35" rows="1" id="category"></textarea>
		<br /> <br />
		<textarea name="text" cols="100" rows="5" class="tweet-box"></textarea>
		<br /> <input type="submit" value="投稿">（1000文字まで）
	</form>
	<form action="top" method="get">
	<input type="submit" value="戻る">
	</form>

</body>
</html>

WebContent/signup.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ユーザー登録</title>
</head>

<body>
<body bgcolor="	#FFFF00">
	<font size=6>ユーザー登録画面</font>
	<div class="main-contents">
		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>
		<form action="signup" method="post">
			<br /> <label for="name">名前（10字以内)</label> <br /> <input
				name="name" id="name" /><br /> <br /> <label for="login_id">アカウント名(半角英数字6-20字以内)</label>
			<br /> <input name="login_id" id="login_id" /> <br /> <br /> <label
				for="password">パスワード(半角文字6-20字以内)</label> <br /> <input
				name="password" type="password" id="password" /> <br /> <br /> <label
				for="passwordConfirm">パスワード(確認用)</label> <br /> <input
				name="passwordConfirm" type="password" id="passwordConfirm" /><br />
			<br /> <label for="branch_code">支店</label><br /> <input
				name="branch_code" /><br /> <br /> <label for="department">部署・役職</label><br />
			<input name="department" /><br /> <label for="authority">ユーザーの状態</label> <br />
			<input name="authority" type="authority" id="authority" />
			<br /> <input type="submit" value="登録" /> <br /> <a href="login.jsp">戻る</a>
		</form>
		<div class="copyright">Copyright(c)Your Name</div>
	</div>
</body>
</body>

</html>

WebContent/top.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ホーム画面</title>
</head>
<body>
	<div class="profile">
		<div class="name">
			<h2>
				<c:out value="${loginUser.name}" />

				さんようこそ
			</h2>
		</div>
	</div>


	<a href="newpost.jsp">新規投稿</a>
	<br />
	<br />
	<br />



	<div class="posts">
		<c:forEach items="${posts}" var="post">
			<div class="post">
				<div class="login_id-name">
					<font size=4><span class="login_id"><c:out
								value="${post.loginId}" /></span> <span class="name"> <c:out
								value="${post.name}" /></span></font><br>

				</div>
				<div class="title">
					title：
					<c:out value="${post.title}" />
				</div>
				<div class="category">
					category：
					<c:out value="${post.category}" />
				</div>
				<div class="text">
					<font size=4> <c:out value="${post.text}" /><br>
					<br>
					</font>
				</div>
			</div>
		</c:forEach>
	</div>





	<c:if test="${ not empty loginUser }">

		<a href="logout">ログアウト</a>
	</c:if>

	<br />
	<a href="login.jsp">戻る</a>
</body>
</html>